# Generated by Django 4.1 on 2023-09-24 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FallType',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='FallHistory',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('fall_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fallmon.falltype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fallmon.user')),
            ],
        ),
    ]
