# Generated by Django 4.1 on 2023-12-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallmon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fallhistory',
            options={'verbose_name': 'FallHistory', 'verbose_name_plural': 'FallHistories'},
        ),
        migrations.AlterModelOptions(
            name='falltype',
            options={'verbose_name': 'FallType', 'verbose_name_plural': 'FallTypes'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
