# Generated by Django 4.1 on 2023-12-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallmon', '0002_alter_fallhistory_options_alter_falltype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falltype',
            name='name',
            field=models.CharField(default='', max_length=256, unique=True),
        ),
    ]
