# Generated by Django 4.1 on 2023-12-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallmon', '0004_alter_falltype_name_alter_user_id_alter_user_pw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falltype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
