# Generated by Django 4.1 on 2023-12-20 11:07

from django.db import migrations
from pathlib import Path
import os, json

BASE_DIR = Path(__file__).resolve().parent.parent.parent
INITIAL_DATA_PATH = 'initial_data.json'



def initialize_fall_type(apps, schema_editor):
    FallType = apps.get_model("fallmon", "FallType")
    with open(os.path.join(BASE_DIR, INITIAL_DATA_PATH)) as initial_data:
        fall_types = json.loads(initial_data.read())
        for fall_type in fall_types['FallType']:
            FallType.objects.get_or_create(name=fall_type)


class Migration(migrations.Migration):

    dependencies = [
        ('fallmon', '0006_alter_fallhistory_id_alter_falltype_id_alter_user_id'),
    ]

    operations = [migrations.RunPython(initialize_fall_type)
    ]
